### PR TITLE
Write about CI & Code health checks in the Docs

### PR DESCRIPTION
**Pull request by thoat**
As suggested by @jwflory [here](https://github.com/unicef/magicbox-maps-prototype/issues/10), I started a draft to fill in [two sections](https://magicbox.readthedocs.io/en/latest/admin/github-workflow.html#set-up-continuous-integration-ci) in the GitHub Workflow article for our ReadTheDocs:

- Set up continuous integration
- Set up code health checks with CodeClimate

This is still a work in progress but @jwflory and everyone feels free to jump in if you find certain sentences too complicated to read or some procedures just plain wrong. 

I hope to finish this either by the end of this week (Jul 9-13) or early next week (Jul 16-20).

### CODE REVIEW

**Comment by jwflory** [comment]
@thoat The content looks good to me – if you want me to review the final content, let me know and I'm happy to do so. :slightly_smiling_face: 

One note that I realized I forgot to put in the contributing guidelines: when writing sentences in the docs, it's convenient to write each sentence on a new line. This is awkward to write, but when it comes to reviewing changes to the docs, it makes reviewing the diff in a pull request really easy. I would recommend putting each sentence on a new line.

**Comment by jwflory** [comment]
@thoat Yup, no problem. To be fair, it's not a widely-practiced convention, but I think it's more practical – it makes reading diffs so much easier.

Also, this could be a good thing to make note of in the contributing guidelines for the docs. :slightly_smiling_face:

**Comment by jwflory** [comment]
Since #40 was merged, it introduces some merge conflicts with this PR. I recommend rebasing this branch against the current master branch of the repository. Rebasing is a convenient way of pulling in new changes to a project since you added work, apply them to the project, and then try to put your changes back on top of the git history.

I recommend reading [this blog post](https://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/ "Don't Be Scared of git rebase") or checking out the [Open edX lesson](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request "How to Rebase a Pull Request") on rebasing if you haven't done it before. These were both really helpful for me. :slightly_smiling_face:

**Comment by thoat** [comment]
Thank you for the heads-up @jwflory ! And thank you for pointing out the direction and resources!

**Pull request merged**
